server:
  port: 8089

eureka:
  instance:
   hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: second-microservice
          uri: http://localhost:8087/
          predicates:
            - Path=/product/**  
            - Method=GET,POST 
        - id: third-microservice
          uri: http://localhost:9898/
          predicates:
            - Path=/user/**
            - Method=GET,POST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "authorization"